jdk: openjdk8
script:
  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter &&
  chmod +x ./cc-test-reporter &&
  ./cc-test-reporter before-build &&
  ./gradlew test &&
  ./gradlew jacocoTestReport &&
  ./gradlew assemble &&
  mkdir -p ~/junit/ &&
  find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \; &&
  JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml     --input-type jacoco &&
  ./cc-test-reporter upload-coverage