name: Build

on:
  push: 
    branches-ignore: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pre-build
      run:  chmod +x ./gradlew
    - name: build
      run: ./gradlew build
